### ISSUE TITLE
Unclear instruction for channel id

### ISSUE THREAD

**Issue by TheScreechingBagel** [Kcnkcn12/YouTube-Transcipt-Scraper#1]
The URL for a channel such as Kurzgesagt – In a Nutshell no longer has the ID, and instead is https://www.youtube.com/c/inanutshell
The solution for me was to open page source and find the channel id there, at the bottom of the page

**Comment by Kcnkcn12** [comment]
After searching for solutions, I found that the YouTube API does not support finding a channel based on a custom url (youtube.com/c/channel_custom_url)

Google's response to the issue: [https://issuetracker.google.com/issues/165676622](https://issuetracker.google.com/issues/165676622)
> Status: Won't Fix (Infeasible)

I can either
- implement scraping the webpage to get the channel id similar to how you did
- ask the user to perform a workaround of clicking on any video, clicking on the channel, and getting the new url

I have added webpage scraping to the script in order to get the channel id similar to how you did it. However, this requires another library to be installed. On account of this added dependency, would you prefer this method or manually ask the user to get the channel id using the workaround?

---

Otherwise, I have changed the script for a full url input and added functionality for legacy usernames (youtube.com/user/legacy_username) and channel id (youtube.com/channel/channel_id).
